on: push
name: labels-management
jobs:
  labels:
    name: labels-management
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1.0.0
      - name: gitHub-labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
